#!/bin/bash

function failIfCommandNotExist(){
    if ! command -v $1 &> /dev/null
    then
        echo "command \"$1\" could not be found."
        exit 1
    fi
}

failIfCommandNotExist yarn
cd transpiler
yarn install
yarn link
cd ../app
yarn install
yarn link transpiler
